### ISSUE TITLE
Upgrade to Wagtail 2.x

### ISSUE THREAD

**Issue by amercader** [okfn/rtei#30]
The main consideration is that Wagtail 2.x only supports Python 3

- [x] Upgrade to Django 1.11: Should be straight-forward as we are on 1.10.8
- [x] Upgrade to Wagtail 1.13 ([notes](https://docs.wagtail.io/en/v2.2.2/releases/1.13.html)): Nothing worrying here
- [x] Upgrade to Wagtail-modeltranslation 0.9.0 ([upgrade notes](https://github.com/infoportugal/wagtail-modeltranslation#upgrade-considerations-v08))
- [x] Upgrade to Python 3, run lib2to3 or whatever is needed, set up tests to run Python 3.7
- [ ] Upgrade to Django 2.1 ([notes](https://docs.djangoproject.com/en/2.1/releases/2.0/))
- [ ] Upgrade to latest Wagtail 2.x ([notes](https://docs.wagtail.io/en/v2.2.2/releases/2.0.html#upgrade-considerations))
- [x] Upgrade [django-wagtail-feeds](https://github.com/chrisdev/django-wagtail-feeds) to 0.1.0
- [ ] :beers:

**Comment by brew** [comment]
Wagtail-modeltranslations 0.9.0 doesn't support Django 2.0. This is because it depends on django-modeltranslations which doesn't support Django 2.0 yet.

So, we can get Django to 1.11.18, and as a consequence, we can update Wagtail to 2.3, but not the latest 2.4, which drops support for Django 1.11.

**Comment by brew** [comment]
Travis doesn't yet support Python 3.7, so using 3.6 for Travis and Heroku.
